import 'package:get/get.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'si_LK': {
          'ADD NEW CROP DAMAGE': 'නව වගා හානියක් දැනුම් දෙන්න',
          'New': 'නව',
          'Incidents': 'සිදුවීම්',
          'incident(s)': 'සිදුවීම(ම්)',
          'In-Progress': 'සක්‍රිය',
          'Approved': 'අනුමත',
          'Rejected': 'ප්‍රතික්ෂේපිත',
          'My Incident Log': 'සිදුවීම් සටහන',
          'Reviewed Incidents': 'සම්පූර්ණ කළ සිදුවීම්',
          'My Profile': 'ගිණුම් තොරතුරු',
          'Personal Info': 'පුද්ගලික තොරතුරු',
          'Farm Info': 'ගොවිපල තොරතුරු',
          'Bank Details': 'බැංකු තොරතුරු',
          'Name': 'නම',
          'NIC': 'ජා.හැ. අංකය',
          'Email Address': 'ඊමේල් ලිපිනය',
          'Mobile Number': 'දුරකථන අංකය',
          'Farm Name': 'ගොවිපල නම',
          'Address': 'ලිපිනය',
          'Reg. Number': 'ලියාපදිංචි අංකය',
          'Bank Name': 'බැංකුව',
          'Account Number': 'ගිණුම් අංකය',
          'Date Added': 'එකතු කළ දිනය',
          'Inform new crop damage': 'නව හානි දැනුම් දීම',
          'Damage Type': 'හානි වර්ගය',
          'Select Category': 'වර්ගය තෝරන්න',
          'Select Type': 'වර්ගය තෝරන්න',
          'Affected Area (Acres)': 'බලපෑමට ලක් වූ ප්රදේශය (අක්කර)',
          'Enter number of acres': 'අක්කර ගණන ඇතුලත් කරන්න',
          'Description': 'විස්තර',
          'Describe the incident in details': 'සිද්ධිය විස්තර කරන්න',
          'Upload Photos/ Videos': 'ඡායාරූප/වීඩියෝ උඩුගත කරන්න',
          'Minimum of 3 evidences should be uploaded':
              'අවම වශයෙන් සාක්ෂි 3ක් උඩුගත කළ යුතුය',
          'Photos/ Videos': 'ඡායාරූප/වීඩියෝ',
          'Invalid': 'වලංගු නැත.',
          'Please fill all fields': 'කරුණාකර සියලුම ක්ෂේත්‍ර පුරවන්න',
          'Please select at least 3 photos/videos':
              'කරුණාකර අවම වශයෙන් ඡායාරූප/වීඩියෝ 3ක්වත් තෝරන්න',
          'Create Complaint': 'පැමිණිල්ලක් සාදන්න',
          'Are you sure?': 'තහවුරු කරනවාද?',
          'All changes will be lost': 'සියලු වෙනස්කම් අහිමි වනු ඇත',
          'Cancel': 'අවලංගු කරන්න',
          'Confirm': 'තහවුරු කරන්න',
          'Nr of Acres': 'අක්කර ගණන',
          'Comments': 'අදහස්',
          'Rs.': 'රු.',
          'Amount Payed': 'ගෙවූ මුදල',
          'Accepted Date': 'භාරගත් දිනය',
          'Rejected Date': 'ප්‍රතික්ෂේප කළ දිනය',
          'Reviewed Date': 'සම්පූර්ණ කළ දිනය',
        },
        'en_US': {
          'ADD NEW CROP DAMAGE': 'ADD NEW CROP DAMAGE',
          'New': 'New',
          'Incidents': 'Incidents',
          'Incident(s)': 'Incident(s)',
          'In-Progress': 'In-Progress',
          'Approved': 'Approved',
          'Rejected': 'Rejected',
          'My Incident Log': 'My Incident Log',
          'Reviewed Incidents': 'Reviewed Incidents',
          'My Profile': 'My Profile',
          'Personal Info': 'Personal Info',
          'Farm Info': 'Farm Info',
          'Bank Details': 'Bank Details',
          'Name': 'Name',
          'NIC': 'NIC',
          'Email Address': 'Email Address',
          'Mobile Number': 'Mobile Number',
          'Farm Name': 'Farm Name',
          'Address': 'Address',
          'Reg. Number': 'Reg. Number',
          'Bank Name': 'Bank Name',
          'Account Number': 'Account Number',
          'Date Added': 'Date Added',
          'Inform new crop damage': 'Inform new crop damage',
          'Damage Type': 'Damage Type',
          'Select Category': 'Select Category',
          'Select Type': 'Select Type',
          'Affected Area (Acres)': 'Affected Area (Acres)',
          'Enter number of acres': 'Enter number of acres',
          'Description': 'Description',
          'Describe the incident in details':
              'Describe the incident in details',
          'Upload Photos/ Videos': 'Upload Photos/ Videos',
          'Minimum of 3 evidences should be uploaded':
              'Minimum of 3 evidences should be uploaded.',
          'Photos/ Videos': 'Photos/ Videos',
          'Invalid': 'Invalid',
          'Please fill all fields': 'Please fill all fields',
          'Please select at least 3 photos/videos':
              'Please select at least 3 photos/videos',
          'Create Complaint': 'Create Complaint',
          'Are you sure?': 'Are you sure?',
          'All changes will be lost': 'All changes will be lost',
          'Cancel': 'Cancel',
          'Confirm': 'Confirm',
          'Nr of Acres': 'Nr of Acres',
          'Comments': 'Comments',
          'Rs.': 'Rs.',
          'Amount Payed': 'Amount Payed',
          'Accepted Date': 'Accepted Date',
          'Rejected Date': 'Rejected Date',
          'Reviewed Date': 'Reviewed Date',
        },
      };
}
